#!/bin/sh

sed -i '/# ------------------------ >8 ------------------------/,$d' "$1"
sed -i 's/[ 	]\+$//' "$1"
sed -i '/^#/d' "$1"
cat -s "$1" | sponge "$1"
sed -i '1{/^$/d}' "$1"
sed -i '${/^$/d}' "$1"

wc -l "$1"
echo FAIL

cp "$1" "COMMIT_MESSAGE"

exit 1

